# Generated by Django 2.2.7 on 2019-11-07 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articlepagegalleryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticlePageGalleryImage',
        ),
    ]
