# Generated by Django 2.2.7 on 2019-11-11 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191109_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Publish Date'),
        ),
    ]
