# Generated by Django 2.2.7 on 2019-11-06 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='bodys',
        ),
    ]
