# Generated by Django 2.2.7 on 2019-12-26 06:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner',
            field=wagtail.core.fields.StreamField([('featured', wagtail.core.blocks.StructBlock([('thumbnails', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())])))]))], blank=True, null=True),
        ),
    ]
