# Generated by Django 2.2.8 on 2019-12-27 00:46

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191226_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('featured', wagtail.core.blocks.StructBlock([('thumbnails', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())])))])), ('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True))])), ('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Add your text', required=True))])), ('richtext', streams.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
