# Generated by Django 2.2.8 on 2019-12-27 04:44

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191227_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('featured', wagtail.core.blocks.StructBlock([('thumbnails', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(page_type=['blog.ArticlePage'], required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]), max_num=3))])), ('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True))])), ('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Add your text', required=True))])), ('richtext', streams.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
