# Generated by Django 2.2.7 on 2019-11-12 00:20

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title', streams.blocks.RichTextBlock()), ('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Add your text', required=True))])), ('richtext', streams.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
