# Generated by Django 2.2.7 on 2019-11-12 01:26

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_auto_20191112_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True))])), ('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Add your text', required=True))])), ('richtext', streams.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
